/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.structure.Graph;

import java.util.Map;

public class App {

    public static void main(String[] args) {
      Graph<String> stringGraph = new Graph<>();
      stringGraph.addNode("A");
      stringGraph.addNode("B");
      stringGraph.addNode("C");
      stringGraph.addNode("D");

      stringGraph.addEdge("A", "B", 25);
      stringGraph.addEdge("A", "C", 15);
      stringGraph.addEdge("C", "D", 35);

      Map<String, Integer> neighbors = stringGraph.getNeighbors("A");
      System.out.println(neighbors);
      Map<String, Integer> neighbors2 = stringGraph.getNeighbors("C");
      System.out.println(neighbors2);
      System.out.println(stringGraph.size());
      System.out.println(stringGraph);
      System.out.println(stringGraph.getNodes());
    }
}
