/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import BST.BTS;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  public void canInstantiate(){
    BTS<Integer> integerBTS = new BTS<>();

    assertTrue(integerBTS.isEmpty());
  }

  @Test
  public void hasOneNode(){
    BTS<Integer> integerBTS = new BTS<>();

    integerBTS.add(45);
    assertFalse(integerBTS.isEmpty());
  }

  @Test
  public void canAddLiftAndRightNode(){
    BTS<Integer> integerBTS = new BTS<>();

    integerBTS.add(45);
    integerBTS.add(50);
    integerBTS.add(43);

    assertEquals(50, integerBTS.getRoot().getRight().getData(),"The Method should add to the lift and to the right sides");
    assertEquals(43, integerBTS.getRoot().getLeft().getData(),"The Method should add to the lift and to the right sides");
  }

  @Test
  public void findMaxTester(){
    BTS<Integer> integerBTS = new BTS<>();

    integerBTS.add(45);
    integerBTS.add(50);
    integerBTS.add(43);

    try {
      assertEquals(50, integerBTS.findMax(), "The method should return the maximum value");
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
