/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package navigator;

import navigator.struture.Navigator;

public class App {
    public static void main(String[] args) {
      Navigator<String> navigator = new Navigator<>();

      navigator.go("Tariq");
      navigator.go("rahaf");
      navigator.go("Osaid");
      navigator.go("Mohammad");


      System.out.println(navigator.back());
      System.out.println(navigator.forward());
      System.out.println(navigator.forward());
      System.out.println(navigator.back());
    }
}
