/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import BST.BTS;

public class App {

  public static void main(String[] args) {

    BTS<Integer> integerBTS = new BTS<>();
    integerBTS.Add(44);
    integerBTS.Add(4);
    integerBTS.Add(63);
    integerBTS.Add(22);
    integerBTS.Add(34);
    integerBTS.Add(72);
    System.out.println(integerBTS.contains(55));
    System.out.println(integerBTS.contains(4));
  }
}
