/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import BST.BTS;

public class App {

  public static void main(String[] args) {

    BTS<Integer> integerBTS = new BTS<>();
    integerBTS.add(44);
    integerBTS.add(4);
    integerBTS.add(63);
    integerBTS.add(22);
    integerBTS.add(34);
    integerBTS.add(72);
    try {
      System.out.println(BTS.breadthFirst(integerBTS));
    } catch (Exception e) {
      e.printStackTrace();
    }
//    System.out.println(integerBTS.contains(55));
//    System.out.println(integerBTS.contains(4));
//    try {
//      System.out.println(integerBTS.findMax());
//    } catch (Exception e) {
//      e.printStackTrace();
//    }
  }
}
