/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int BinarySearch(int[] arr, int target){
      Arrays.sort(arr);
      System.out.println("After sorting => " + Arrays.toString(arr));
      return BinarySearch(arr, 0, arr.length -1, target);
    }

    private int BinarySearch(int[] arr, int low, int high, int target){
      int midIdx = low + (high -low) / 2;

      if( low == high && target != arr[midIdx])
        return -1;
      else if(target < arr[midIdx])
        return BinarySearch(arr, low, midIdx - 1, target);
      else if(target > arr[midIdx])
        return BinarySearch(arr, midIdx + 1, high, target);
      else
        return midIdx;
    }
}
