/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  public void isEmpty() {
    LinkedList list = new LinkedList();
    assertNull(list.getHead(), "When instantiating liked list object it should be empty");
  }

  @Test
  public void canInsert() {
    LinkedList list = new LinkedList();
    list.insert("macRosX");
    assertTrue(list.includes("macRosX"), "The method should return true");
  }

  @Test
  public void isFirst(){
    LinkedList list = new LinkedList();
    list.insert("A");
    list.insert("B");
    list.insert("C");
    assertEquals("C", list.getHead().getData(), "The method should return 'C'");
  }

  @Test
  public void insertMultiple(){
    LinkedList list = new LinkedList();
    list.insert("A");
    list.insert("B");
    list.insert("C");
    assertTrue(list.includes("A"), "The method should return true");
    assertTrue(list.includes("B"), "The method should return true");
    assertTrue(list.includes("C"), "The method should return true");
  }

  @Test
  public void isFund(){
    LinkedList list = new LinkedList();
    list.insert("S");
    assertTrue(list.includes("S"), "The method should return true");
  }

  @Test
  public void isNtFund(){
    LinkedList list = new LinkedList();
    list.insert("S");
    list.insert("A");
    assertFalse(list.includes("B"), "The method should return true");
  }

  @Test
  public void getCollection(){
    LinkedList list = new LinkedList();
    list.insert("S");
    list.insert("A");
    list.insert("D");
    list.insert("G");
    assertEquals("Head -> G -> D -> A -> S -> NULL", list.toString(), "");
  }
}
