/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  public void insertionSort(){
    int[] array = new int[]{8,4,23,42,16,15};
    App.insertionSort(array);

    assertArrayEquals(array,new int[]{4,8,15,16,23,42});
  }
  @Test
  public void mergeSort(){
    int[] array = new int[]{8,4,23,42,16,15};
    App.mergeSort(array);

    assertArrayEquals(array,new int[]{4,8,15,16,23,42});
  }
}
