/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

  public static void main(String[] args) {
    LinkedList list = new LinkedList();
    list.insert("S");
    list.insert("A");
    list.insert("D");
    list.append("YY");
    list.insert("GGG");
    list.insert("AX");
    list.insert("DT");
    list.append("ZZ");
    list.insert("RTX");

    LinkedList list2 = new LinkedList();
    list2.insert("Q");
    list2.insert("D");
    list2.insert("DD");
    list2.append("FX");
    list2.append("FR");
    list2.append("TX");
    list2.insertBefore("FX", "MN");
    list2.append("JG");
    list2.append("PL");
    list2.append("OO");
    list2.insertBefore("FX", "MX");

    System.out.println(list);
    System.out.println(list2);
    LinkedList list3 = null;
    try {
      list3 = LinkedList.zipLists(list, list2);
    } catch (Exception e) {
      e.printStackTrace();
    }
    System.out.println("The Zipped version => " + list3);

  }
}
