/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StacksAndQueues;

import Queue.Queue;
import Stack.Stack;

public class App {
  public static void main(String[] args) {
    queueDemo();
    stackDemo();
  }

  public static void queueDemo() {
    Queue<String> queue = new Queue<String>();

    queue.enqueue("Max");
    queue.enqueue("Ros");
    System.out.println(queue);
    try {
      System.out.println(queue.peek());
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void stackDemo() {
    Stack<Integer> stack = new Stack<Integer>();

    stack.push(14);
    stack.push(2);
    stack.push(9);
    System.out.println(stack);

    try {
      System.out.println(stack.peek());
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
